name: Next.js Build and Discord Notification

on:
  push:
    branches:
      - main 

jobs:
  build_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1 

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Send Discord notification
        if: ${{ always() }}
        run: |
          STATUS="success"
          COLOR=65280
          if [[ ${{ failure() }} == 'true' ]]; then
            STATUS="failure"
            COLOR=16711680
          fi

          formatted_date=$(node -e "console.log(new Date().toLocaleString('th-TH', { timeZone: 'Asia/Bangkok', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }))")

          curl -X POST -H "Content-Type: application/json" -d '{
            "embeds": [
              {
                "color": '"$COLOR"',
                "fields": [
                  {
                    "name": "Project Name",
                    "value": "${{ github.event.repository.name }}",
                    "inline": false
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  },
                  {
                    "name": "Time",
                    "value": "'"$formatted_date"'",
                    "inline": true
                  },
                  {
                    "name": "Status",
                    "value": "'"$STATUS"'",
                    "inline": true
                  }
                ]
              }
            ]
          }' https://discord.com/api/webhooks/1138334232217923685/CTbqDRcQn6TwXGyaAqxbSuU1-M8erA3iopU5EHYamxF3C5eXDbUyxMXWkTYBR8s9GKfx
