name: Next.js Build and Discord Notification

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1 

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Check for build errors
        run: |
          if [ -f ./.next/failed ]; then
            echo "Build failed" && exit 1
          fi
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+07:00"

      - name: Send Discord notification on failure
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
          "embeds": [
              {
                "color": 16711680,
                "fields": [
                  {
                    "name": "project name",
                    "value": "${{ github.event.repository.name }}",
                    "inline": false
                  },
                  {
                    "name": "branch",
                    "value": "${{ github.ref_name }}",
                    "inline": false
                  },
                  {
                    "name": "เวลา",
                    "value": "${{ github.event.repository.updated_at}}",
                    "inline": true
                  },
                  {
                    "name": "สถานะ",
                    "value": "Success",
                    "inline": true
                  }
                ]
              }
            ]
          }' https://discord.com/api/webhooks/1138334232217923685/CTbqDRcQn6TwXGyaAqxbSuU1-M8erA3iopU5EHYamxF3C5eXDbUyxMXWkTYBR8s9GKfx
        